[Feature] Add multiple price sources to collateral oracle
Mirror-Protocol/mirror-contracts pull request #37
Opened 2021-05-20 09:26 UTC by csanti

### Overview

We want to add to the collateral oracle 2 additional price sources:
- Fixed price: When registering the collateral the owner specifies a fixed rate.
- Band oracle: Query the price directly from band protocol's oracle.

Because now we have collaterals that have completely different logic when obtaining the price, we need to substitute the current generic `query_request` for a `source_type`:

```
pub enum SourceType {
    TerraOracle {
        query_request: Binary,
    },
    BandOracle {
        query_request: Binary,
    },
    FixedPrice {
        price: Decimal,
    },
    Terraswap {
        query_request: Binary,
    }
} 
```

### Querying price from Band Oracle

Band oracle has the peculiarity of returning the price as a `Uint128` instead of a `Decimal` [(Band oracle doc)](https://github.com/bandprotocol/cosmwasm-std-reference-doc#struct-types) The `Uint128` contains the price multiplied by `1e18`.

Parsing the `Uint128` can be tricky because the conversion operation, would result in a `uint128` overflow. If instead we use 256 variant, it still could have the possibility of overflowing.

Therefore, in this implementation I opted to parse it as a string to safely move the decimal point.

2021-05-21 03:37 UTC, YunSuk-Yeo requested changes
LGTM, changing the Binary to SourceType looks very good.

band & terra oracle query has updated time data, so we can use that data to give return error response when it has not been updated for too long time.

2021-05-21 03:37 UTC, YunSuk-Yeo commented on contracts/mirror_collateral_oracle/src/querier.rs
> +pub struct BandOracleResponse {
I have example query here https://lcd.terra.dev/wasm/contracts/terra1mwshjfdth2xtpx7gvnwpzhks2clr9z7h9m0e0f/store?query_msg=%7B%22get_reference_data%22:%7B%22base_symbol%22:%22AAPL%22,%22quote_symbol%22:%22USD%22%7D%7D

2021-05-21 06:50 UTC, csanti commented on contracts/mirror_collateral_oracle/src/querier.rs
> +pub struct BandOracleResponse {
Added requested changes

2021-05-21 06:51 UTC, csanti commented
Added the requested changes. Now collateral oracle returns last_updated parameter. The price age is checked by mint contract.

2021-05-24 02:04 UTC, YunSuk-Yeo approved these changes

2021-05-24 02:06 UTC, merged